ERROR:duecredit:Failed to import duecredit due to No module named 'duecredit'
INFO:__main__:Generating new Dataset.
INFO:nimare.meta.kernel:Temporary file written to /home/tsalo006/.nimare/temporary_files/MKDAKernelih_u7ex320210315T104734
INFO:nimare.utils:Shared path detected: "/"
INFO:nimare.meta.kernel:Removing temporary file: /home/tsalo006/.nimare/temporary_files/MKDAKernelih_u7ex320210315T104734
INFO:nimare.utils:Shared path detected: "/"
/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/utils.py:208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lambda x: x.split(shared_path)[1] if isinstance(x, str) else x
INFO:__main__:Initializing CorrelationDecoder.
INFO:__main__:Fitting CorrelationDecoder.
INFO:nimare.meta.kernel:Temporary file written to /home/tsalo006/.nimare/temporary_files/MKDAKernelchfo3thn20210315T120554
INFO:nimare.meta.kernel:Removing temporary file: /home/tsalo006/.nimare/temporary_files/MKDAKernelchfo3thn20210315T120554
INFO:nimare.utils:Shared path detected: "/"
/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/utils.py:208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lambda x: x.split(shared_path)[1] if isinstance(x, str) else x
INFO:nimare.utils:Shared path detected: "/"
INFO:nimare.meta.cbma.mkda:Loading pre-generated MA maps for Dataset 1.
INFO:nimare.meta.cbma.mkda:Loading pre-generated MA maps for Dataset 2.
Traceback (most recent call last):
  File "listings_figures_and_tables_part3.py", line 56, in <module>
    decoder.fit(ns_dset_first5000)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/base.py", line 417, in fit
    self._fit(dataset)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/decode/continuous.py", line 188, in _fit
    self.meta_estimator.fit(feature_dset, nonfeature_dset)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/meta/cbma/base.py", line 671, in fit
    maps = self._fit(dataset1, dataset2)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/meta/cbma/mkda.py", line 219, in _fit
    ma_maps2 = self.masker.transform(self.inputs_["ma_maps2"])
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/nifti_masker.py", line 408, in transform_single_imgs
    dtype=self.dtype
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/nifti_masker.py", line 58, in filter_and_mask
    dtype=dtype)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/base_masker.py", line 99, in filter_and_extract
    memory_level=memory_level)(imgs)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/nifti_masker.py", line 31, in __call__
    dtype=img_data_dtype(imgs)), imgs.affine)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/masking.py", line 761, in apply_mask
    ensure_finite=ensure_finite)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/masking.py", line 804, in _apply_mask_fmri
    copy=True)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/_utils/numpy_conversions.py", line 110, in as_ndarray
    ret = _asarray(arr, dtype=dtype, order=order)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/_utils/numpy_conversions.py", line 27, in _asarray
    ret = np.asarray(arr, dtype=dtype, order=order)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/numpy/core/_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
numpy.core._exceptions.MemoryError: Unable to allocate 33.3 GiB for an array with shape (91, 109, 91, 4956) and data type int64
